# Generated by Django 3.2.16 on 2022-11-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='date_cut',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
