# Generated by Django 3.2.16 on 2022-11-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0002_cut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='cut',
            new_name='cuts',
        ),
    ]
