# Generated by Django 3.2.16 on 2022-11-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0002_alter_roll_roll_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='roll_balance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
