# Generated by Django 3.2.16 on 2022-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0003_alter_roll_roll_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='cut_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_size',
            field=models.CharField(max_length=10),
        ),
    ]
