# Generated by Django 3.2.16 on 2022-11-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0004_auto_20221120_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='cut_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_size',
            field=models.IntegerField(),
        ),
    ]
